# Simplified Supabase config for development/staging
# Minimal setup - just the essentials

project_id = "AdeptTime"

[api]
enabled = true
port = 54321
schemas = ["public"]
max_rows = 1000

[api.tls]
enabled = false

[db]
port = 54322
major_version = 17

# Disable pooler for simplicity
[db.pooler]
enabled = false

[db.migrations]
enabled = true
schema_paths = []

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

# Disable network restrictions for dev
[db.network_restrictions]
enabled = false

# Disable realtime for now (can enable later if needed)
[realtime]
enabled = false

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

# Disable email testing server
[inbucket]
enabled = false

# Basic storage only (no image transformation)
[storage]
enabled = true
file_size_limit = "10MiB"

# Simple auth - no external providers, no MFA, no complex rules
[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = false
enable_signup = true
enable_anonymous_sign_ins = false
minimum_password_length = 6

# Simple rate limits
[auth.rate_limit]
email_sent = 10
sign_in_sign_ups = 100
token_refresh = 300

[auth.email]
enable_signup = true
enable_confirmations = false

# Disable SMS
[auth.sms]
enable_signup = false

# Disable all external auth providers
[auth.external.apple]
enabled = false

# Disable edge runtime
[edge_runtime]
enabled = false

# Disable analytics
[analytics]
enabled = false

# Disable experimental features
[experimental]
orioledb_version = ""
